server:
  port: 0

spring:
  config:
    import:
      - application-file.yml
  application:
    name: consultation-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3305/devtalk-consultation?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: love1994
    hikari:
      maximum-pool-size: 8
      connection-timeout: 10000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        default_batch_fetch_size: 100
        show_sql: true #show sql
#    redis:
#      host: localhost
#      port: 6379


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
